---
name: build_linux

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  main:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.arch }} artefacts
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - run: |
          uname -a | tee -a "${{ matrix.arch }}-stats.txt"
          echo "Page size: $(getconf PAGESIZE)" | tee -a "${{ matrix.arch }}-stats.txt"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *-stats.txt

